import { project } from 'views/admin/tasklists/adminDataTypes';

export const data: project = [
  {
    id: 1,
    title: 'Project1',
    description: 'Project 1',
    status: '80',
    client: 'asdf1',
    dueDate: '01-10-23',
    repository: 'www.repo1.com',
    tasks: [
      {
        id: 1,
        task: 'task 1',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 2,
        task: 'task 2',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 3,
        task: 'task 3',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 4,
        task: 'task 4',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 5,
        task: 'task 5',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 6,
        task: 'task 6',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 2,
    title: 'Project2',
    description: 'Project 2',
    status: '70',
    client: 'asdf2',
    dueDate: '02-10-23',
    repository: 'www.repo2.com',
    tasks: [
      {
        id: 7,
        task: 'task 7',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 8,
        task: 'task 8',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 9,
        task: 'task 9',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 10,
        task: 'task 10',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 11,
        task: 'task 11',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 12,
        task: 'task 12',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 3,
    title: 'Project3',
    description: 'Project 3',
    status: '0',
    client: 'asdf3',
    dueDate: '03-10-23',
    repository: 'www.repo3.com',
    tasks: [
      {
        id: 13,
        task: 'task 13',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 14,
        task: 'task 14',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 15,
        task: 'task 15',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 16,
        task: 'task 16',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 17,
        task: 'task 17',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 18,
        task: 'task 18',
        status: 1,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 4,
    title: 'Project4',
    description: 'Project 4',
    status: '30',
    client: 'asdf4',
    dueDate: '04-10-23',
    repository: 'www.repo4.com',
    tasks: [
      {
        id: 19,
        task: 'task 19',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 20,
        task: 'task 20',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 21,
        task: 'task 21',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 22,
        task: 'task 22',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 23,
        task: 'task 23',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 24,
        task: 'task 24',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 5,
    title: 'Project5',
    description: 'Project 5',
    status: '40',
    client: 'asdf5',
    dueDate: '05-10-23',
    repository: 'www.repo5.com',
    tasks: [
      {
        id: 25,
        task: 'task 25',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 26,
        task: 'task 26',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 27,
        task: 'task 27',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 28,
        task: 'task 28',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 29,
        task: 'task 29',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 30,
        task: 'task 30',
        status: -1,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 6,
    title: 'Project6',
    description: 'Project 6',
    status: '60',
    client: 'asdf6',
    dueDate: '06-10-23',
    repository: 'www.repo6.com',
    tasks: [
      {
        id: 31,
        task: 'task 31',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 32,
        task: 'task 32',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 33,
        task: 'task 33',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 34,
        task: 'task 34',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 35,
        task: 'task 35',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 36,
        task: 'task 36',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
];
